class Constants:
    TILES_Y = 50
    TILES_X = 38
    TILE_HEIGHT = 16
    TILE_WIDTH = 16

    WINDOW_HEIGHT = TILES_Y * TILE_HEIGHT
    WINDOW_WIDTH = TILES_X * TILE_WIDTH

    MAP_SCALE = 5

    MUSIC_FADEOUT_SPEED = 200 # miliseconds

    MAP_ORIGIN_X = 360
    MAP_ORIGIN_Y = 280